---
- hosts: prod-ingest_handlers
  gather_facts: False
  remote_user: pmena
  become: yes
  become_user: asadev
  become_method: su
  tasks:
    - name: run a script to check status
      script: ./manage_ingest_handler.sh status
