---
- hosts: ooi-redmine_server
  gather_facts: False
  remote_user: pmena
  become: yes
  become_user: redmine
  become_method: su
  tasks:
    - name: run a script to gather redmine data from Rutgers
      script: ./pull_ooi_redmine_data.sh 

- hosts: localhost
  connection: local
  tasks:
    - name: run a script to copy redmine data between Rutgers and WHOI
      script: ./xfer_ooi_redmine_data.sh 

- hosts: whoi-redmine_server
  gather_facts: False
  remote_user: pmena
  become: yes
  become_user: redmine
  become_method: su
  tasks:
    - name: run a script to put the copied redmine data on WHOI server
      script: ./push_ooi_redmine_data.sh 

- hosts: whoi-redmine_server
  gather_facts: False
  remote_user: pmena
  become: yes
  become_user: root
  become_method: su
  tasks:
    - name: run a script to restart postgress and httpd on WHOI server
      script: ./restart_ooi_redmine_servers.sh 
