---
- hosts: uat-edex01
  gather_facts: False
  remote_user: pmena
  become: yes
  become_user: asadev
  become_method: su
  tasks:
    - name: run a script to check status
      script: ./edex01_release_prep.sh 
