---
- hosts: uat-ingest_handlers
  gather_facts: False
  remote_user: pmena
  become: yes
  become_user: asadev
  become_method: su
  tasks:
    - name: run a script to update the ingest engine conda code
      script: ./ingest_handler_update.sh 
