---
- hosts: uat-ingest_handlers
  gather_facts: False
  remote_user: pmena
  become: yes
  become_user: asadev
  become_method: su
  tasks:
    - name: run a script to move ingest handler logs
      script: ./test_ingest_log_move.sh 
